POST http://localhost:3000/api/v1/admin_auth
Content-Type: application/json
Accept: application/json

{
  "email": "admin2@example.com",
  "password": "admin123",
  "password_confirmation": "admin123"
}

###

POST http://localhost:3000/api/v1/admin_auth/sign_in
Content-Type: application/json
Accept: application/json

{
  "email": "admin@example.com",
  "password": "admin123"
}

###

